webapp:
  Secrets:
    - category: resteam
      name: APIGateway-CommerceServiceKey 
    - category: resteam
      name: APIGateway-SupplyChainServiceKey 
  AppSettings:
    LocationServiceBaseUrl: 'https://api-dev.columbia.com/locations/v1/locations/'
    RetailProdServiceBaseUrl: 'https://api-dev.columbia.com/retail-product-api/v1/retailmasters/'
    CommercePricingServiceBaseUrl: 'https://api-dev.columbia.com/commercepricing/v1/commercepricing/'
    ImageServiceBaseUrl: 'https://api-dev.columbia.com/ContentHubImage/api/Image/v2/images/'